### PR TITLE
Show institution information before connecting

### PR DESCRIPTION
**Pull request by jornane**
When choosing a CAT profile, the user is prompted for a password. The same also happens when the user sideloads a profile which requires username/password. The username/password screen doesn't contain information about the profile being installed.

Similarily, when side-loading a profile with client certificate, the app should show what it's about to install before it actually does so. And when asking for a PIN we should also see information about the institution.

The eap-config file can contain the name of the institution, a logo and contact information, so I was thinking we have three screens that can be presented to the user;

It should also be easier to implement the flow from Phase I correctly using these screens; the app works in two stages, stage 1 is to obtain 

Here are some proposals for the screens that we would need.

(screen 1, no user info needed; user/pass or passphrase already provided)
```
<img LOGO>
<txt TITLE>




[btn Connect to network]



<link Support contact information>
```

(screen 2, username/password required)
```
<img LOGO>
<txt TITLE>

Username: [input]
Password: [input passphrase]

[btn Connect to network]

<txt (Note: if the connection fails, please check your password)>

<link Support contact information>
```

(screen 3, passphrase required, the passphrase should show as text and not as •••••)
```
<img LOGO>
<txt TITLE>


Passphrase: [input passphrase]

[btn Connect to network]



<link Support contact information>
```

### CODE REVIEW

**Comment by amachadogarcia** [comment]
Fixed in commit 0866fecd4245d0d595f4adeaf6831c973e4ad877

**Comment by CarlosFJ** [comment]
Fixed in commit https://github.com/geteduroam/ionic-app/pull/71/commits/c2a998bc605eacd9ae7877ea6656b472ea99cf7c

**Comment by jornane** [comment]
Tested only on iOS, but after clicking "Click here for support", a modal view comes up

* It has buttons for web, phone or e-mail, but it doesn't show what the actual address or number is.
* The modal is not dismissible without pressing one of the buttons.

**Comment by CarlosFJ** [comment]
Fix in commit https://github.com/geteduroam/ionic-app/pull/71/commits/b6a34ab83f18769d6b56ab3c55f04b51158f6cb9

**Pull request merged**
