### PR TITLE
Fix/validation eap config

### PR DESCRIPTION
**Pull request by amachadogarcia**
The parsing of the eap-config file has been modified accepting the possibility that the clientCertificate has format and encoded as attributes.
This branch has been merged with branch # 47 so it has been modified to the new clientId, also adapting the application to be able to open this new clientId in the browser.
Error screens have been added at the end of the configuration according to the response obtained from the plugin.
In the plugin, one more treatment of a possible error has been added and also in case of obtaining an error, the execution of the plugin will be stopped sending an error to ionic.

### CODE REVIEW

**Comment by jornane** [comment]
Works! I noticed that the app still accepts `<ClientCertificate>` without attributes, it doesn't need to. Can you remove support for it, or add a comment somewhere in the code about this?

**Comment by jornane** [comment]
Works partially. Upon unparsable eap-config, the app show an error message, as intended. This was tested both for the CAT flow and the OAuth flow.

However, there are two issues with this solution.

**Issue A**

When using the CAT flow, the app shows a username/password screen, only to replace it with the error message a few seconds later. It should not show a username/password screen until the eap-config is downloaded, check the app flow again!

**Issue B**

There is a close button under the error message, which seems unresponsive in the UI and triggers the following error:

```
⚡️  To Native ->  App exitApp -1
ERROR MESSAGE:  {"message":"not implemented","errorMessage":""}
```

Please be advised that closing the application is not possible on iOS. On iOS, you must send the user back to the main page.

**Comment by jornane** [comment]
**Issue F**

If eduroam is not available at the users' location, but the configuration succeeds, `plugin.wifieapconfigurator.error.network.notLinked` is returned; this must not be handled as an error

**Comment by amachadogarcia** [comment]
In the last commit the following has been fixed: the eap-config check is done once the desired profile has been selected. If not valid, it will be sent to an error screen. On the contrary, if valid we check that eap-type contains and depending on it we redirect to one flow or another. In case the flow is of cat type we will check if the username and password are already coming and then we will configure the network directly, in case the user is not asked to do so via the form. In case the flow is of type oauth we will configure the network without requesting data.

**Pull request merged**
